### ISSUE TITLE
Payload generation for Sanger QC metrics failed due to incorrect inference of normal BAS

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/variant-calling-tools#21]
## Describe the bug
Payload generation for Sanger QC metrics step failed with the follow message:
```
Traceback (most recent call last):
    File "/tools/payload-gen-variant-calling.py", line 299, in <module>
      main(args)
    File "/tools/payload-gen-variant-calling.py", line 256, in main
      file_info = get_files_info(f, args.wf_short_name, args.wf_version, somatic_or_germline, normal_analysis, tumour_analysis)
    File "/tools/payload-gen-variant-calling.py", line 166, in get_files_info
      os.symlink(os.path.abspath(file_to_upload), dst)
  FileExistsError: [Errno 17] File exists: 'TEST-PR.DO250183.SA610229.wxs.20200427.aln.cram.bas_metrics.tgz' -> 'out/TEST-PR.DO253000.SA612999.wxs.20200429.sanger-wxs.somatic
.bas_metrics.tgz'
```
## Steps To Reproduce
In `rdpc-dev` environment, use `"tumour_aln_analysis_id": "48dc80b2-dcec-4f73-9c80-b2dcecef73d5"` and `"normal_aln_analysis_id": "4dc53c51-7b48-4843-853c-517b48584389"` as input aligned sequences to run Sanger WXS calling pipeline.

## Expected behaviour
Payload generation for qc_metrics should not fail.

## Cause and possible fix
The root cause is here: https://github.com/icgc-argo/data-processing-utility-tools/blob/payload-gen-variant-calling.0.1.0.0/tools/payload-gen-variant-calling/payload-gen-variant-calling.py#L82. The line assumes input BAS file name contains proper IDs for project/donor/sample in order to differentiate normal BAS and tumour BAS, which a kind of strong assumption. In the case this assumption is correct, we can see failure like mentioned above. A safer alternative is to have `tumour` or `normal` explicitly in the BAS file name, similar to contamination file pattern:  `r'.+?\.normal.contamination_metrics.tgz'`. This would be much more reliable way to differentiate `tumour` and `normal` BAS.

Easiest fix is to have BAS filename include `tumour` or `normal` explicitly. This requires change in `generate_bas` to add this information.

**Comment by junjun-zhang** [comment]
addressed by #22
